[package]
name = "sapphire"
version = "0.1.0"
edition = "2021"

[dependencies]
ahash = "0.8.1"
bitflags = "1.3.2"
serde = { version = "1.0.150", features = ["derive"], optional = true }
slotmap = "1.0.6"
smallvec = "1.10.0"
static_assertions = "1.1.0"

[features]
default = ["enable-serde"]
enable-serde = ["dep:serde", "slotmap/serde", "smallvec/serde", "ahash/serde"]