[package]
name = "sapphire"
version = "0.1.0"
edition = "2021"

[dependencies]
ahash = "0.8.1"
bitflags = "1.3.2"
num-derive = "0.3.3"
num-traits = "0.2.15"
serde = { version = "1.0.151", features = ["derive"], optional = true }
serde_test = { version = "1.0.151", optional = true }
smallbitvec = "2.5.1"
smallvec = "1.10.0"
static_assertions = "1.1.0"

[features]
default = ["enable-serde"]
enable-serde = ["dep:serde", "dep:serde_test", "smallvec/serde", "ahash/serde"]