//======---------------------------------------------------------------======//
//                                                                           //
// Copyright 2022-2023 Evan Cox <evanacox00@gmail.com>. All rights reserved. //
//                                                                           //
// Use of this source code is governed by a BSD-style license that can be    //
// found in the LICENSE.txt file at the root of this project, or at the      //
// following link: https://opensource.org/licenses/BSD-3-Clause              //
//                                                                           //
//======---------------------------------------------------------------======//

/// A "register allocator" that puts everything on the stack, only loading
/// values to perform operations.
///
/// This should not be used for actual codegen, this is intended to be a
/// "known-good" allocator that can be used to compare the code generated by
/// other allocators against for correctness.
pub struct StackRegAlloc {}
